### ISSUE TITLE
Этот класс ничего не должен знать про кнопку

### ISSUE THREAD

**Issue by coursar** [azatmagdeev/LikerApp#2]
https://github.com/azatmagdeev/LikerApp/blob/95fc2c9606d1d092a201fe43aa8daea70b844c67/docs/js/lib.js#L26

Эта кнопка должна создаваться в другом месте.

Поскольку вы её один раз уже создали, то каждый раз при пересоздании списка вы заново навешиваете на эту кнопку eventListener:

https://github.com/azatmagdeev/LikerApp/blob/95fc2c9606d1d092a201fe43aa8daea70b844c67/docs/js/app.js#L49-L53

Из-за этого, у вас на кнопке получается очень много EventListener'ов и вам приходится делать stop propagation.

**Comment by azatmagdeev** [comment]
ага! точно. Спасибо
